default to prod, when no parameters are passed
toolforge/buildservice pull request #14
Opened 2022-11-14 13:48 UTC by komlasapaty

This is for T321162 (allow running deploy.sh without passing a parameter)

2022-11-15 22:30 UTC, david-caro commented
This looks nice, I'll test it when I'm back 👍

2022-11-17 16:38 UTC, david-caro requested changes
Just a couple deleted lines that were needed.

2022-11-17 16:38 UTC, david-caro commented on deploy.sh
> -    local environment="${1?No environment passed}"
This is still needed, otherwise `$environment` would be empty (let me know if you want a longer explanation)

2022-11-17 16:38 UTC, david-caro commented on deploy.sh
> +      deploy/$environment/auth-patch.yaml.template > deploy/$environment/auth-patch.yaml
This template file (`auth-path.yaml.template`) only exists in the dever environment, so we still need the `if` block too

2023-01-18 19:00 UTC, NdibeRaymond commented
I will merge this PR and then submit a follow up patch to fix all the issues raised above

2023-01-18 19:01 UTC, merged